import type { UnitClassDef, Preset } from './types'

export const UNIT_CLASSES: UnitClassDef[] = [
  {
    id: 'knight',
    name: 'Knight',
    icon: '\u2694',
    mass: 1.4,
    hp: 100,
    contactDamage: 14,
    baseSpeed: 5.5,
    radius: 18,
    color: '#5A6577',
    accentColor: '#8899AA',
    weaponType: 'sword',
    weaponLength: 48,
    ability: {
      type: 'area_blast',
      cooldownMs: 6000,
      range: 55,
      damage: 22,
      blastRadius: 55,
    },
  },
  {
    id: 'archer',
    name: 'Archer',
    icon: '\u{1F3F9}',
    mass: 0.7,
    hp: 55,
    contactDamage: 4,
    baseSpeed: 6.0,
    radius: 14,
    color: '#2D7A4F',
    accentColor: '#4CAF6E',
    weaponType: 'bow',
    weaponLength: 36,
    ability: {
      type: 'projectile',
      cooldownMs: 2200,
      range: 180,
      damage: 16,
      projectileSpeed: 6,
      projectileRadius: 3,
    },
  },
  {
    id: 'viking',
    name: 'Viking',
    icon: '\u{1FA93}',
    mass: 1.3,
    hp: 95,
    contactDamage: 16,
    baseSpeed: 5.0,
    radius: 18,
    color: '#4A3228',
    accentColor: '#7A5A42',
    weaponType: 'axe',
    weaponLength: 40,
    ability: {
      type: 'area_blast',
      cooldownMs: 5500,
      range: 60,
      damage: 18,
      blastRadius: 60,
    },
  },
  {
    id: 'paladin',
    name: 'Paladin',
    icon: '\u2728',
    mass: 1.5,
    hp: 130,
    contactDamage: 9,
    baseSpeed: 4.5,
    radius: 20,
    color: '#D4930D',
    accentColor: '#F5B800',
    weaponType: 'shield',
    weaponLength: 32,
    ability: {
      type: 'heal_aura',
      cooldownMs: 7000,
      range: 70,
      damage: 0,
      healAmount: 18,
      blastRadius: 70,
    },
  },
  {
    id: 'cavalry',
    name: 'Cavalry',
    icon: '\u{1F40E}',
    mass: 2.0,
    hp: 90,
    contactDamage: 20,
    baseSpeed: 6.5,
    radius: 22,
    color: '#6B3410',
    accentColor: '#A0653A',
    weaponType: 'lance',
    weaponLength: 56,
    ability: {
      type: 'area_blast',
      cooldownMs: 5000,
      range: 45,
      damage: 18,
      blastRadius: 45,
    },
  },
]

export const PRESETS: Preset[] = [
  {
    name: 'Knight Duel',
    red: { knight: 1 },
    blue: { knight: 1 },
  },
  {
    name: 'Viking vs Archer',
    red: { viking: 1 },
    blue: { archer: 1 },
  },
  {
    name: 'Paladin vs Cavalry',
    red: { paladin: 1 },
    blue: { cavalry: 1 },
  },
  {
    name: '3v3 Skirmish',
    red: { knight: 1, archer: 1, viking: 1 },
    blue: { knight: 1, archer: 1, viking: 1 },
  },
  {
    name: '5v5 Battle',
    red: { knight: 2, archer: 1, viking: 1, paladin: 1 },
    blue: { knight: 2, archer: 1, viking: 1, paladin: 1 },
  },
  {
    name: 'Full War',
    red: { knight: 4, archer: 3, viking: 2, paladin: 2, cavalry: 1 },
    blue: { knight: 4, archer: 3, viking: 2, paladin: 2, cavalry: 1 },
  },
]
